// Export Utilities for QBM Research Platform
// Supports BibTeX, JSON, Markdown, and Print exports

import { saveAs } from "file-saver";

// ============================================================================
// BIBTEX EXPORT
// ============================================================================

export interface BibTeXEntry {
  type: "misc" | "article" | "book" | "inproceedings";
  key: string;
  title: string;
  author?: string;
  year: string;
  howpublished?: string;
  note?: string;
  url?: string;
  surah?: number;
  ayah?: number;
}

export function generateBibTeX(entry: BibTeXEntry): string {
  const fields: string[] = [];

  if (entry.title) fields.push(`  title = {${entry.title}}`);
  if (entry.author) fields.push(`  author = {${entry.author}}`);
  if (entry.year) fields.push(`  year = {${entry.year}}`);
  if (entry.howpublished) fields.push(`  howpublished = {${entry.howpublished}}`);
  if (entry.note) fields.push(`  note = {${entry.note}}`);
  if (entry.url) fields.push(`  url = {${entry.url}}`);

  return `@${entry.type}{${entry.key},
${fields.join(",\n")}
}`;
}

export function generateQBMCitation(
  surah: number,
  ayah: number,
  behavior: string,
  timestamp: Date = new Date()
): string {
  const key = `qbm_${surah}_${ayah}_${behavior.toLowerCase().replace(/\s+/g, "_").replace(/[^a-z0-9_]/g, "")}`;

  return generateBibTeX({
    type: "misc",
    key,
    title: `Behavioral Analysis of Quran ${surah}:${ayah} - ${behavior}`,
    author: "{Quranic Behavioral Matrix (QBM)}",
    year: timestamp.getFullYear().toString(),
    howpublished: "\\url{https://qbm.research.platform}",
    note: `Generated from QBM Research Platform. Surah ${surah}, Ayah ${ayah}. Behavior: ${behavior}. Retrieved ${timestamp.toISOString().split("T")[0]}`,
  });
}

export function downloadBibTeX(content: string, filename: string = "qbm-citation.bib") {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  saveAs(blob, filename);
}

// ============================================================================
// JSON EXPORT
// ============================================================================

export interface ProofExportData {
  query: string;
  timestamp: string;
  surah: number;
  ayah: number;
  behavior: {
    id: string;
    ar: string;
    en: string;
  };
  agent?: {
    id: string;
    ar: string;
    en: string;
  };
  organ?: {
    id: string;
    ar: string;
    en: string;
  };
  axes11: Record<string, string>;
  tafsirSources: string[];
  graphContext: {
    connectedNodes: number;
    edgeTypes: string[];
  };
  validation: {
    score: number;
    benchmark: string;
  };
}

export function downloadJSON(data: any, filename: string = "qbm-export.json") {
  const content = JSON.stringify(data, null, 2);
  const blob = new Blob([content], { type: "application/json;charset=utf-8" });
  saveAs(blob, filename);
}

// ============================================================================
// TEXT/MARKDOWN EXPORT
// ============================================================================

export function generateProofMarkdown(data: ProofExportData): string {
  const axesTable = Object.entries(data.axes11)
    .map(([axis, value]) => `| ${axis} | ${value} |`)
    .join("\n");

  const tafsirList = data.tafsirSources.map((s, i) => `${i + 1}. ${s}`).join("\n");

  return `# QBM Research Proof

## ${data.behavior.ar} (${data.behavior.en})

**Query:** ${data.query}
**Reference:** Quran ${data.surah}:${data.ayah}
**Generated:** ${data.timestamp}

---

## Behavioral Classification

| Attribute | Value (AR) | Value (EN) |
|-----------|------------|------------|
| Behavior | ${data.behavior.ar} | ${data.behavior.en} |
| Agent | ${data.agent?.ar || "—"} | ${data.agent?.en || "—"} |
| Organ | ${data.organ?.ar || "—"} | ${data.organ?.en || "—"} |

---

## 11-Axis Classification

| Axis | Value |
|------|-------|
${axesTable}

---

## Tafsir Sources Consulted

${tafsirList}

---

## Graph Context

- **Connected nodes:** ${data.graphContext.connectedNodes}
- **Relationship types:** ${data.graphContext.edgeTypes.join(", ")}

---

## Validation

- **Score:** ${data.validation.score}%
- **Benchmark:** ${data.validation.benchmark}

---

*Generated by Quranic Behavioral Matrix (QBM) Research Platform*
*Based on the Bouzidani 11-Axis Framework*
*200/200 Benchmark Validated*
`;
}

export function downloadMarkdown(content: string, filename: string = "qbm-proof.md") {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  saveAs(blob, filename);
}

// ============================================================================
// PRINT-TO-PDF HELPER
// ============================================================================

export function printProofPage() {
  // This triggers browser's print dialog which can save as PDF
  window.print();
}

// ============================================================================
// COPY TO CLIPBOARD
// ============================================================================

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error("Failed to copy to clipboard:", err);
    return false;
  }
}
